name: EE build and push

on:
  push:
    branches:
      - main
    paths:
      - 'execution-environment/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses: kenmoini/ansible-ee-builder/.github/workflows/build-ee-base.yml@main
    with:
      REGISTRY_HOSTNAME: quay.io
      REGISTRY_PATH: kenmoini
      EE_IMAGE_NAME: 'openshift-agent-install-ee'
      EE_IMAGE_TAG: 'latest'
      EE_FOLDER_NAME: 'execution-environment'
      EE_FILE_NAME: execution-environment.yaml
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
      # REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      # REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
